### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by mostlyfireproof** [mostlyfireproof/porygonbot#1]
/home/ubuntu/porygonbot/src/commands/pokemon/abilitly.js:25
        if text=='help'{
           ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /home/ubuntu/node_modules/require-all/index.js:52:46
    at Array.forEach (<anonymous>)
    at requireAll (/home/ubuntu/node_modules/require-all/index.js:34:9)
    at /home/ubuntu/node_modules/require-all/index.js:40:38

**Comment by mostlyfireproof** [comment]
I just deleted the code that broke it
